"use client";

const KEY_FUMIGANTS = "packing-ui-fumigation-fumigants";
const KEY_METHODOLOGIES = "packing-ui-fumigation-methodologies";
const KEY_CERT_TEMPLATES = "packing-ui-fumigation-certificate-templates";
const KEY_RECORD_TEMPLATES = "packing-ui-fumigation-record-templates";

const CERTIFICATE_FIELDS = [
  "Template name",
  "Customer",
  "Commodity",
  "Fumigant",
  "Dosage",
  "Exposure",
  "Location",
  "Fumigator",
  "Date issued",
];

const RECORD_FIELDS = [
  "Monitoring start",
  "Monitoring intervals",
  "Gas readings (top/middle/base)",
  "Clearance reading",
  "Fumigator sign-off",
  "Inspector verification",
];

export const DEFAULT_FUMIGANTS = [
  {
    id: 1,
    code: "PH3",
    name: "Phosphine",
    chemicalFamily: "Metal phosphide",
    activeConstituent: "Phosphine gas",
    productForm: "Cylinder",
    reEntryPpm: "0.3",
    defaultUnit: "ppm",
  },
  {
    id: 2,
    code: "MBR",
    name: "Methyl Bromide",
    chemicalFamily: "Halocarbon",
    activeConstituent: "Bromomethane",
    productForm: "Gas",
    reEntryPpm: "5",
    defaultUnit: "ppm",
  },
];

export const DEFAULT_METHODOLOGIES = [
  {
    id: 1,
    name: "Container phosphine export",
    version: "v1.0",
    effectiveDate: "2026-03-01",
    fumigantId: 1,
    applicationMethods: ["In-container"],
    minTemperature: "10",
    maxTemperature: "35",
    minExposureUnit: "hours",
    minExposure: "24",
    dosageUnit: "ppm",
    dosageGuide: "20-35ppm baseline by temperature band",
    restraint: "Do not vent near occupied packing bays.",
    ventilationPeriod: "2",
    withholdingPeriod: "0",
    reEntryPpm: "0.3",
    safetyNotes: "Wear calibrated PH3 monitor and PPE.",
  },
];

export const DEFAULT_CERTIFICATE_TEMPLATES = [
  {
    id: 1,
    name: "Default Export Certificate",
    headerText: "Mahonys Packing Pty Ltd",
    footerText: "Generated by Packing ERP",
    body: "Certificate issued for completed fumigation treatment.",
    fields: CERTIFICATE_FIELDS,
    logoDataUrl: "",
    footerLogoDataUrl: "",
  },
];

export const DEFAULT_RECORD_TEMPLATES = [
  {
    id: 1,
    name: "Default Record Sheet",
    headerText: "Mahonys Packing - Fumigation Record",
    footerText: "Record retained for compliance audit.",
    body: "Record all monitoring intervals and final clearance values.",
    includeCertificateFields: true,
    fields: RECORD_FIELDS,
    logoDataUrl: "",
    footerLogoDataUrl: "",
  },
];

function readArray(key, fallback) {
  if (typeof window === "undefined") return [...fallback];
  try {
    const raw = window.localStorage.getItem(key);
    if (!raw) return [...fallback];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [...fallback];
  } catch {
    return [...fallback];
  }
}

function writeArray(key, rows) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(key, JSON.stringify(rows));
}

export function loadFumigants() {
  return readArray(KEY_FUMIGANTS, DEFAULT_FUMIGANTS);
}

export function saveFumigants(rows) {
  writeArray(KEY_FUMIGANTS, rows);
}

export function loadMethodologies() {
  return readArray(KEY_METHODOLOGIES, DEFAULT_METHODOLOGIES);
}

export function saveMethodologies(rows) {
  writeArray(KEY_METHODOLOGIES, rows);
}

export function loadCertificateTemplates() {
  return readArray(KEY_CERT_TEMPLATES, DEFAULT_CERTIFICATE_TEMPLATES);
}

export function saveCertificateTemplates(rows) {
  writeArray(KEY_CERT_TEMPLATES, rows);
}

export function loadRecordTemplates() {
  return readArray(KEY_RECORD_TEMPLATES, DEFAULT_RECORD_TEMPLATES);
}

export function saveRecordTemplates(rows) {
  writeArray(KEY_RECORD_TEMPLATES, rows);
}

export function nextLocalEntityId(rows) {
  return Math.max(0, ...(Array.isArray(rows) ? rows : []).map((row) => Number(row.id) || 0)) + 1;
}

