"use client";

import {
  CERTIFICATE_FIELDS,
  CERTIFICATE_SECTIONS,
  RECORD_FIELDS,
  RECORD_SECTIONS,
} from "@/lib/fumigation-fields";

const KEY_FUMIGANTS = "packing-ui-fumigation-fumigants";
const KEY_METHODOLOGIES = "packing-ui-fumigation-methodologies";
const KEY_CERT_TEMPLATES = "packing-ui-fumigation-certificate-templates";
const KEY_RECORD_TEMPLATES = "packing-ui-fumigation-record-templates";

export { CERTIFICATE_FIELDS, RECORD_FIELDS };

export const DEFAULT_FUMIGANTS = [
  {
    id: 1,
    code: "PH3",
    name: "Phosphine",
    chemicalFamily: "Metal phosphide",
    activeConstituent: "Phosphine gas",
    productForm: "Cylinder",
    reEntryPpm: "0.3",
    defaultUnit: "g/m3",
  },
  {
    id: 2,
    code: "MBR",
    name: "Methyl Bromide",
    chemicalFamily: "Halocarbon",
    activeConstituent: "Bromomethane",
    productForm: "Gas",
    reEntryPpm: "5",
    defaultUnit: "g/m3",
  },
  {
    id: 3,
    code: "SF",
    name: "Sulfuryl Fluoride",
    chemicalFamily: "Sulfonyl fluoride",
    activeConstituent: "Sulfuryl fluoride (SO2F2)",
    productForm: "Cylinder",
    // TLV-TWA per SF methodology §9.1.1 — 3 ppm
    reEntryPpm: "3",
    defaultUnit: "g/m3",
  },
];

export const DEFAULT_METHODOLOGIES = [
  {
    id: 1,
    name: "Container phosphine export",
    version: "v1.0",
    effectiveDate: "2026-03-01",
    fumigantId: 1,
    applicationMethods: ["In-container"],
    minTemperature: "10",
    maxTemperature: "35",
    minExposureUnit: "hours",
    minExposure: "24",
    dosageUnit: "g/m3",
    dosageGuide: "20-35ppm baseline by temperature band",
    restraint: "Do not vent near occupied packing bays.",
    ventilationPeriod: "2",
    withholdingPeriod: "0",
    reEntryPpm: "0.3",
    safetyNotes: "Wear calibrated PH3 monitor and PPE.",
    // SOURCE: Based on AS/NZS 3784 and DAFF phosphine container fumigation guidelines.
    // TODO: Verify exact figures against current approved methodology before live use.
    dosageRanges: [
      { id: 1, minTempC: 10, maxTempC: 15, dosageValue: 2.0, dosageUnit: "g/m3", exposureValue: 240, exposureUnit: "hours" },
      { id: 2, minTempC: 15, maxTempC: 20, dosageValue: 2.0, dosageUnit: "g/m3", exposureValue: 168, exposureUnit: "hours" },
      { id: 3, minTempC: 20, maxTempC: 25, dosageValue: 2.0, dosageUnit: "g/m3", exposureValue: 120, exposureUnit: "hours" },
      { id: 4, minTempC: 25, maxTempC: 35, dosageValue: 2.0, dosageUnit: "g/m3", exposureValue: 96, exposureUnit: "hours" },
    ],
  },
  {
    id: 2,
    name: "Sulfuryl fluoride container fumigation",
    version: "v1.1",
    effectiveDate: "2018-11-01",
    fumigantId: 3,
    applicationMethods: ["In-container", "Sheeted enclosure", "Chamber"],
    minTemperature: "10",
    maxTemperature: "40",
    minExposureUnit: "hours",
    minExposure: "24",
    dosageUnit: "g/m3",
    dosageGuide:
      "See Appendix 3 of the SF methodology — refer Figures 5 & 6 for 24-hour and 12-hour exposure tables.",
    restraint:
      "Approved 3rd-party CT systems must follow that system's dose calculation in lieu of these bands.",
    ventilationPeriod: "2",
    withholdingPeriod: "0",
    reEntryPpm: "3",
    safetyNotes:
      "TLV-TWA 3 ppm. Wear calibrated SF monitor and PPE per SF methodology §2.3.",
    // SOURCE: Sulfuryl fluoride fumigation methodology v1.1 (Nov 2018), DAWR.
    // §10 Documentation + Appendix 3 monitoring tables (Figures 5 & 6 — image-only in
    // the PDF, not extractable as text). dosageRanges intentionally empty —
    // populate from those tables in the methodology editor at
    // /fumigation/fumigation-methodologies before live use. Each band corresponds
    // to a temperature × exposure-period cell in Figures 5/6.
    dosageRanges: [],
  },
];

export const DEFAULT_CERTIFICATE_TEMPLATES = [
  {
    id: 1,
    name: "Default Export Certificate",
    headerText: "Mahonys Packing Pty Ltd",
    footerText: "Generated by Packing ERP",
    body: "Certificate issued for completed fumigation treatment.",
    // Gov-aligned section toggles — every section enabled by default
    sections: CERTIFICATE_SECTIONS.map((s) => s.key),
    // Pre-fills the cert's "Additional declarations" field on Generate
    additionalDeclarationsText: "",
    logoDataUrl: "",
    footerLogoDataUrl: "",
    // Legacy — kept so old snapshots still serialise round-trip; not used by the new document
    fields: CERTIFICATE_FIELDS,
  },
];

export const DEFAULT_RECORD_TEMPLATES = [
  {
    id: 1,
    name: "Default Record Sheet",
    headerText: "Mahonys Packing - Fumigation Record",
    footerText: "Record retained for compliance audit.",
    body: "Record all monitoring intervals and final clearance values.",
    sections: RECORD_SECTIONS.map((s) => s.key),
    logoDataUrl: "",
    footerLogoDataUrl: "",
    // Legacy — kept so old snapshots still serialise round-trip; not used by the new document
    fields: RECORD_FIELDS,
    includeCertificateFields: true,
  },
];

/** Migrate legacy unit strings to the canonical g/m3 form */
function normaliseUnit(u) {
  if (u === "g/m³" || u === "g/m\u00b3") return "g/m3";
  return u;
}

function readArray(key, fallback) {
  if (typeof window === "undefined") return [...fallback];
  try {
    const raw = window.localStorage.getItem(key);
    if (!raw) return [...fallback];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [...fallback];
  } catch {
    return [...fallback];
  }
}

function writeArray(key, rows) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(key, JSON.stringify(rows));
}

export function fumigantItemLabel(item) {
  if (!item) return "";
  const code = String(item.code || "").trim();
  const name = String(item.name || "").trim();
  if (code && name) return `${code} - ${name}`;
  return name || code;
}

/** Resolve the fumigant label shown on pack schedule / packers schedule screens. */
export function resolvePackFumigantDisplay(pack, fumigants = []) {
  if (!pack) return "";

  const fumigantId = pack.fumigantId ?? pack.fumigant_id ?? pack.fumigationDetail?.fumigantId;
  if (fumigantId != null && fumigantId !== "" && Array.isArray(fumigants)) {
    const match = fumigants.find((row) => String(row.id) === String(fumigantId));
    const label = fumigantItemLabel(match);
    if (label) return label;
  }

  const detail = pack.fumigationDetail;
  if (detail && typeof detail === "object") {
    const fromDetail = detail.fumigantName ?? detail.fumigant_name ?? detail.fumigationNotes ?? detail.fumigation_notes;
    const trimmed = String(fromDetail || "").trim();
    if (trimmed) return trimmed;
  }

  const fumigationText = String(pack.fumigation || "").trim();
  if (fumigationText && fumigationText.toLowerCase() !== "required") return fumigationText;

  const timing = String(pack.fumigationTiming ?? pack.fumigation_timing ?? "").trim();
  if (timing) return timing;

  if (pack.fumigationRequired ?? pack.fumigation_required) return "Required";
  return "";
}

export function loadFumigants() {
  const rows = readArray(KEY_FUMIGANTS, DEFAULT_FUMIGANTS);
  return rows.map((row) => ({
    ...row,
    defaultUnit: normaliseUnit(row.defaultUnit),
  }));
}

export function saveFumigants(rows) {
  writeArray(KEY_FUMIGANTS, rows);
}

export function loadMethodologies() {
  const rows = readArray(KEY_METHODOLOGIES, DEFAULT_METHODOLOGIES);
  return rows.map((row) => ({
    dosageRanges: [],
    ...row,
    dosageUnit: normaliseUnit(row.dosageUnit),
    dosageRanges: (row.dosageRanges || []).map((r) => ({
      ...r,
      dosageUnit: normaliseUnit(r.dosageUnit),
    })),
  }));
}

export function saveMethodologies(rows) {
  writeArray(KEY_METHODOLOGIES, rows);
}

export function loadCertificateTemplates() {
  return readArray(KEY_CERT_TEMPLATES, DEFAULT_CERTIFICATE_TEMPLATES);
}

export function saveCertificateTemplates(rows) {
  writeArray(KEY_CERT_TEMPLATES, rows);
}

export function loadRecordTemplates() {
  return readArray(KEY_RECORD_TEMPLATES, DEFAULT_RECORD_TEMPLATES);
}

export function saveRecordTemplates(rows) {
  writeArray(KEY_RECORD_TEMPLATES, rows);
}

export function nextLocalEntityId(rows) {
  return Math.max(0, ...(Array.isArray(rows) ? rows : []).map((row) => Number(row.id) || 0)) + 1;
}
